version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"    # Metro bundler
      - "19000:19000"  # Expo dev tools
      - "19001:19001"  # Expo dev server
      - "19002:19002"  # Expo tunnel
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - expo-network

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    networks:
      - expo-network

networks:
  expo-network:
    driver: bridge
